### PR TITLE
Extract nested attachments (msg in msg)

### PR DESCRIPTION
**Pull request by jbfuzier**
A quick addition to extract attachments from nested msg (an msg attached in a msg is not handled as a standard attachement)

My use case is to extract all the attachment I can to do some analysis on extracted file.

I have not thought on how to handle nested message body, cc, to..

### CODE REVIEW

**Comment by moshekaplan** [comment]
I had the same issue that I was unable to retrieve data for attached MSG files.

Does this chance break any existing functionality?

**Comment by mattgwwalker** [comment]
Please give it a try. I'd love to have feedback. It would greatly help me if you could also include some test msg files that contained msg files as attachments. This would allow us to implement some automated testing for example.

**Comment by moshekaplan** [comment]
Here is a sample file you can use to replicate the issue:
[msg_inside_of_msg.zip](https://github.com/mattgwwalker/msg-extractor/files/593388/msg_inside_of_msg.zip)

Here is my sample code:
```
    fname = sys.argv[1]
    msg = Message(fname)
    for attachment in msg.attachments:
        filename = attachment.longFilename
        # Otherwise use the short filename
        if filename is None:
            filename = attachment.shortFilename
        # Otherwise just make something up!
        if filename is None:
            print "Filename missing"
        print "Size:", len(attachment.data)
```

Output:

> Filename missing
> Size:
> Traceback (most recent call last):
>   File "msg.py", line 536, in <module>
>     print "Size:", len(attachment.data)
> TypeError: object of type 'NoneType' has no len()
>

**Comment by TheElementalOfCreation** [comment]
Fixed in most recent update. If you believe the issue still exists, please open a new issue thread.

**Pull request closed without merging**
