### PR TITLE
Simplify encoding management

### PR DESCRIPTION
**Pull request by pudo**
I've recently started depending on the PyPI version of this again (in alephdata/aleph), and am seeing a lot of errors coming out of encoding of message bodies. This PR is just to make the code for detecting the message string encoding a bit clearer.

I would also like to propose falling back to a default encoding when none has been detected, rather than throwing an error and thus discarding the message entirely. Would this be accepted?

### CODE REVIEW

**Comment by TheElementalOfCreation** [comment]
As far as I am aware, it should not be possible for there to be no encoding detected. Can you please
1) open an issue on this
2) send me some example files (inside of a zip file) so I can inspect the problem myself?

**Comment by pudo** [comment]
Thanks, opened #95.

**Comment by pudo** [comment]
For completeness' sake, here's the exception linked to this PR (weirdly short trace):

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/extract_msg/message.py", line 210, in header
    return self._header
AttributeError: 'Message' object has no attribute '_header'
```

**Comment by TheElementalOfCreation** [comment]
Uh... that exception occurred inside of a try-except block and should have been caught.

**Pull request closed without merging**
