### PR TITLE
Save attachments as unicode

### PR DESCRIPTION
**Pull request by SamuelMarks**
Was getting ascii errors, changing it to this solved all the issues for me. Not sure if you'd rather have it as an optional flag.

### CODE REVIEW

**Comment by TheElementalOfCreation** [comment]
Can you check to see if you ever get the same errors if you use the ExtractMsg.py from my pull request:

https://github.com/mattgwwalker/msg-extractor/pull/33

As my pull request combines many of the others plus has many additions, I would like to try to keep is as close to the top as possible to make sure it actually does get merged into the master branch.

Thank you

**Comment by TheElementalOfCreation** [comment]
@SamuelMarks Correction, can you check to see if you still get errors from the current version (0.18, currently) of ExtractMsg?

**Comment by SamuelMarks** [comment]
Wait why was this one not merged?

**Comment by TheElementalOfDestruction** [comment]
There are a few reasons this was not merged:
1. We are currently on version 0.26.3 and use a completely different file system. Trying to merge this wouldn't work anymore.
2. We implemented this in a completely different way a few versions ago.
3. Our module is meant to be compatible with Python 2.7 and your code was not.

**Comment by SamuelMarks** [comment]
3. It's in Python 2 https://docs.python.org/2/library/codecs.html#codecs.open

**Comment by TheElementalOfDestruction** [comment]
That one is my bad, I missed the line at the top. However, the rest of my points still stand.

**Pull request closed without merging**
