### PR TITLE
make ExtractMsg pip installable

### PR DESCRIPTION
**Pull request by deanmalmgren**
Hey @mattgwwalker, This is really helpful. Thanks for putting this script together.

I'm working on another project ([textract](https://github.com/deanmalmgren/textract)) and it would be really helpful to make it easy to use ExtractMsg. This pull request adds a `setup.py` and also makes it so `ExtractMsg.py` is installed on the system path for binaries (so you can run it from the command line) and also in the python library (so you can import it).

### CODE REVIEW

**Comment by mattgwwalker** [comment]
Hi Dean,

Thanks for your contributions, I am sorry I still haven't got around to
reviewing them.  However, I have someone who would like to pay for a script
to * write *msg files.  If you would like to modify my script, or to start
from scratch, I think both options would be available.  The client is
non-technical and needs this done in one week.

Would you be interested in this work?  I am too busy at the moment to take
it on.

Cheers,

Matthew

**Comment by deanmalmgren** [comment]
Hey Matt,

Thanks for offering to share, but I also don't have bandwidth. And actually, [I could use some help writing a .msg file too](https://github.com/deanmalmgren/textract/pull/87) hahaha. So...if you happen to know anybody that would like to contribute this, please let me know!

Cheers,
Dean

**Comment by mattgwwalker** [comment]
I have access to Outlook, and I've replied to your thread in case that's
helpful.

It's a shame that neither of us have the time to make this happen.

Matthew

**Comment by deanmalmgren** [comment]
Totally agree. If there was someone I could recommend this to, I certainly
would. This kinda feels like something that might be doable through Upwork,
but I have no idea what is involved...

On Mon, Jun 22, 2015 at 4:43 PM Matthew Walker <notifications@github.com>
wrote:

> I have access to Outlook, and I've replied to your thread in case that's
> helpful.
>
> It's a shame that neither of us have the time to make this happen.
>
> Matthew
>
> On 23 June 2015 at 09:37, Dean Malmgren <notifications@github.com> wrote:
>
> > Hey Matt,
> >
> > Thanks for offering to share, but I also don't have bandwidth. And
> > actually, I could use some help writing a .msg file too
> > <https://github.com/deanmalmgren/textract/pull/87> hahaha. So...if you
> > happen to know anybody that would like to contribute this, please let me
> > know!
> >
> > Cheers,
> > Dean
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mattgwwalker/msg-extractor/pull/4#issuecomment-114271357
> >
> > .
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgwwalker/msg-extractor/pull/4#issuecomment-114272293>
> .
>
-- 
*dean malmgren | +1.312.884.9214 *
*partner, data scientist | datascope*

**Comment by deanmalmgren** [comment]
The good news is that I can confirm that this PR works. I just added some installation instructions. I can currently install msg-extractor on the command line using (at the moment, my feature branch):

```sh
pip install https://github.com/deanmalmgren/msg-extractor/zipball/pip-installable
```

When this is merged, you can use the url `https://github.com/mattgwwalker/msg-extractor/zipball/master`, instead. This can be added to `setup.py` scripts by using the `dependency_links` keyword argument.

If you do end up wanting to put this up on pypi, you should be able to do that relatively easily now that you have a setup.py. That will further streamline the installation for others, too.

**Pull request merged**
